[package]
authors = ["C J Silverio <ceejceej@gmail.com>", "Chris Dickinson <chris@neversaw.us>"]
edition = "2018"
name = "boltzmann"
version = "0.1.1"
[dependencies]
anyhow = "1.0.31"
atty = "*"
colored = "*"
include_dir = "0.6.0"
lazy_static = "1.4.0"
log = "*"
loggerv = "*"
ron = "0.6.0"
serde_json = "1.0.53"
structopt = "0.3.14"
subprocess = "*"
tera = "1.3.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.110"
