base_url = "https://www.neversaw.us/scratch/boltzmann"
compile_sass = true
highlight_code = true
highlight_theme = "ir-white"
build_search_index = true
theme = "boltzie"
title = "Boltzmann: A JS HTTP Framework"
insert_anchor_links = true

taxonomies = [
    # You can enable/disable feeds
    {name = "tags", feed = true},
]

[extra]
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/concepts", name = "Concepts"},
    {url = "$BASE_URL/guides", name = "Guides"},
    {url = "$BASE_URL/reference", name = "Reference"},
    {url = "https://github.com/entropic-dev/boltzmann", name = "GitHub"},
]

after_dark_title = "Boltzmann: A JS HTTP Framework"
